language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt

notifications:
  email:
    recipients:
      - ahmetbulut@sehir.edu.tr
    on_success: never # default: change
    on_failure: always # default: always